name: PBW Agent (Amazon Best Sellers)

on:
  schedule:
    - cron: "17 5 * * *"        # daglig 05:17 UTC (~07:17 Oslo)
  workflow_dispatch: {}          # også mulig å kjøre manuelt

permissions:
  contents: write                # må ha write for å pushe endringer

concurrency:
  group: pbw-agent
  cancel-in-progress: false

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Repoet er “vanilla” uten package.json – installer bare det vi trenger.
      - name: Install deps (cheerio)
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install cheerio@1

      - name: Kjør agent (generer data/ og r/)
        env:
          ASSOC_TAG: ${{ secrets.AMAZON_ASSOCIATE_TAG }}      # OneLink-taggen din
          PUBLIC_BASE_URL: https://purebloomworld.com         # kan endres ved behov
        run: |
          node scripts/pbw_agent.mjs

      - name: Sjekk om noe endret seg
        id: changes
        run: |
          if git diff --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit & push endringer
        if: steps.changes.outputs.no_changes == 'false'
        run: |
          git config user.name  "pbw-agent"
          git config user.email "pbw-agent@users.noreply.github.com"
          git add -A
          git commit -m "chore(agent): refresh bestsellers"
          git push