name: PBW Agent (hourly)
on:
  schedule:
    - cron: "0 * * * *"   # hver hele time
  workflow_dispatch:       # manuell kjøring
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install httpx
      - name: Generate top sellers + Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          AFFIL_TAG: ${{ secrets.AFFIL_TAG }}   # valgfri
        run: |
          python - << 'PY'
          import os, json, httpx, datetime
          # TODO: bytt ut mock med ekte feed senere
          items = [{"id": f"B0TEST{i:02d}", "title": f"Mock Product #{i}"} for i in range(1, 21)]
          data = {"ts": datetime.datetime.utcnow().isoformat(), "items": items}
          os.makedirs("data", exist_ok=True)
          with open("data/top_sellers.json","w",encoding="utf-8") as f:
              json.dump(data, f, indent=2, ensure_ascii=False)
          wh = os.getenv("DISCORD_WEBHOOK","").strip()
          if wh:
              try: httpx.post(wh, json={"content": f"🛒 PBW Actions: oppdatert {len(items)} toppselgere"}, timeout=10)
              except Exception: pass
          PY
      - name: Commit & push
        run: |
          git config user.name "PBW Actions"
          git config user.email "bot@pbw.local"
          git add data/top_sellers.json
          git commit -m "Update top_sellers (Actions)" || echo "No changes"
          git push
