name: PBW Agent (Amazon Best Sellers)

on:
  schedule:
    - cron: "*/30 * * * *"  # hver 30. min
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installer kun cheerio, direkte (vi unngår cache/lock-støy)
      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm install cheerio@^1

      - name: Run agent (oppdaterer /data)
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          AFFIL_TAG: ${{ secrets.AFFIL_TAG }}
        run: node scripts/pbw_agent.mjs

      - name: Commit & push changes
        run: |
          git config user.name "PBW Actions"
          git config user.email "bot@pbw.local"
          git add -A
          git commit -m "PBW Agent output" || echo "No changes"
          git push